/* google.js — Google 帳號與 Drive 備份 */
'use strict';
const GOOGLE_SCOPES='openid email profile https://www.googleapis.com/auth/drive.file';let googleAccessToken='',googleTokenExpiresAt=0,googleTokenClient=null;
function googleConnected(){return googleAccessToken&&Date.now()<googleTokenExpiresAt}
async function connectGoogle(){const clientId=state.settings.google.clientId;if(!clientId)return showToast('請先在 Google Drive 設定輸入 Client ID');if(!window.google?.accounts?.oauth2)return showToast('Google 元件尚未載入');return new Promise((resolve,reject)=>{googleTokenClient=google.accounts.oauth2.initTokenClient({client_id:clientId,scope:GOOGLE_SCOPES,callback:async response=>{if(response.error)return reject(new Error(response.error));googleAccessToken=response.access_token;googleTokenExpiresAt=Date.now()+(Number(response.expires_in||3600)-60)*1000;try{const profile=await googleFetch('https://www.googleapis.com/oauth2/v3/userinfo');state.settings.account={name:profile.name||'',email:profile.email||'',picture:profile.picture||''};await saveState();updateHeader();renderRoute();resolve()}catch(e){reject(e)}}});googleTokenClient.requestAccessToken({prompt:'consent'})}).catch(e=>showToast(e.message))}
function disconnectGoogle(){if(googleAccessToken&&window.google?.accounts?.oauth2)google.accounts.oauth2.revoke(googleAccessToken,()=>{});googleAccessToken='';googleTokenExpiresAt=0;state.settings.account={name:'',email:'',picture:''};scheduleSave();updateHeader();renderRoute()}
async function googleFetch(url,options={}){if(!googleConnected())throw new Error('Google 連線已過期，請重新連接');const headers=new Headers(options.headers||{});headers.set('Authorization',`Bearer ${googleAccessToken}`);const response=await fetch(url,{...options,headers});if(!response.ok)throw new Error((await response.json().catch(()=>({}))).error?.message||`Google API 錯誤 ${response.status}`);const type=response.headers.get('content-type')||'';return type.includes('json')?response.json():response}
async function ensureGoogleFolder(){const config=state.settings.google;if(config.folderId)return config.folderId;const query=encodeURIComponent(`name='${config.folderName.replaceAll("'","\\'")}' and mimeType='application/vnd.google-apps.folder' and trashed=false`);const data=await googleFetch(`https://www.googleapis.com/drive/v3/files?q=${query}&fields=files(id,name)&spaces=drive`);if(data.files?.[0])config.folderId=data.files[0].id;else{const folder=await googleFetch('https://www.googleapis.com/drive/v3/files?fields=id',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:config.folderName,mimeType:'application/vnd.google-apps.folder'})});config.folderId=folder.id}await saveState();return config.folderId}
async function syncGoogleDrive({silent=false}={}){try{if(!googleConnected())await connectGoogle();if(!googleConnected())return;const folderId=await ensureGoogleFolder();const payload=JSON.stringify({app:'民宿營運管理系統',version:APP_VERSION,exportedAt:new Date().toISOString(),data:state},null,2);const name='民宿營運_系統還原備份.json';const query=encodeURIComponent(`name='${name}' and '${folderId}' in parents and trashed=false`);const found=await googleFetch(`https://www.googleapis.com/drive/v3/files?q=${query}&fields=files(id)&spaces=drive`);const boundary=`homestay_${Date.now()}`;const metadata=found.files?.[0]?{}:{name,parents:[folderId]};const body=`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(metadata)}\r\n--${boundary}\r\nContent-Type: application/json\r\n\r\n${payload}\r\n--${boundary}--`;const id=found.files?.[0]?.id;await googleFetch(id?`https://www.googleapis.com/upload/drive/v3/files/${id}?uploadType=multipart`:'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart',{method:id?'PATCH':'POST',headers:{'Content-Type':`multipart/related; boundary=${boundary}`},body});if(!silent)showToast('Google Drive 同步完成')}catch(e){showToast(e.message)}}
